---

- name: Check existence of matrix-mautrix-wsproxy service
  stat:
    path: "{{ matrix_systemd_path }}/matrix-mautrix-wsproxy.service"
  register: matrix_mautrix_wsproxy_service_stat

- name: Ensure matrix-mautrix-wsproxy is stopped
  service:
    name: matrix-mautrix-wsproxy
    state: stopped
    daemon_reload: yes
  when: "matrix_mautrix_wsproxy_service_stat.stat.exists"

- name: Ensure matrix-mautrix-wsproxy.service doesn't exist
  file:
    path: "{{ matrix_systemd_path }}/matrix-mautrix-wsproxy.service"
    state: absent
  when: "matrix_mautrix_wsproxy_service_stat.stat.exists"

- name: Ensure systemd reloaded after matrix-mautrix-wsproxy.service removal
  service:
    daemon_reload: yes
  when: "matrix_mautrix_wsproxy_service_stat.stat.exists"
