---

# If the matrix-synapse role is not used, `matrix_synapse_role_executed` won't exist.
# We don't want to fail in such cases.
- name: Fail if matrix-synapse role already executed
  fail:
    msg: >-
      The matrix-bridge-mautrix-wsproxy role needs to execute before the matrix-synapse role.
  when: "matrix_synapse_role_executed|default(False)"

- set_fact:
    matrix_mautrix_wsproxy_requires_restart: false

- name: Ensure Mautrix wsproxy image is pulled
  docker_image:
    name: "{{ matrix_mautrix_wsproxy_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_mautrix_wsproxy_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_mautrix_wsproxy_docker_image_force_pull }}"

- name: Ensure Mautrix wsproxy paths exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - "{{ matrix_mautrix_wsproxy_base_path }}"
    - "{{ matrix_mautrix_wsproxy_config_path }}"
    - "{{ matrix_mautrix_wsproxy_data_path }}"

- name: Check if an old matrix state file exists
  stat:
    path: "{{ matrix_mautrix_wsproxy_base_path }}/mx-state.json"
  register: matrix_mautrix_wsproxy_stat_mx_state

- name: Ensure mautrix-wsproxy config.yaml installed
  copy:
    content: "{{ matrix_mautrix_wsproxy_configuration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_wsproxy_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure wsproxy labels installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ matrix_mautrix_wsproxy_base_path }}/labels"
    mode: 0640
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure mautrix-wsproxy registration.yaml installed
  copy:
    content: "{{ matrix_mautrix_wsproxy_registration|to_nice_yaml }}"
    dest: "{{ matrix_mautrix_wsproxy_config_path }}/registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-mautrix-wsproxy.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-mautrix-wsproxy.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-mautrix-wsproxy.service"
    mode: 0644
  register: matrix_mautrix_wsproxy_systemd_service_result

- name: Ensure systemd reloaded after matrix-mautrix-wsproxy.service installation
  service:
    daemon_reload: yes
  when: "matrix_mautrix_wsproxy_systemd_service_result.changed"

- name: Ensure matrix-mautrix-wsproxy.service restarted, if necessary
  service:
    name: "matrix-mautrix-wsproxy.service"
    state: restarted
  when: "matrix_mautrix_wsproxy_requires_restart|bool"
